Allow repeated calls to connect and disconnect
encode/databases pull request #379
Opened 2021-09-01 17:05 UTC by sondrelg

Replaces assertions with early returns as discussed in https://github.com/encode/databases/issues/359.

2021-09-01 17:25 UTC, sondrelg commented
Looks like the test suite fails from a drop in coverage. I'll happily add tests for this, but do you think this is otherwise mergable seeing that no tests actually failed here @aminalaee? 🙂

2021-09-01 17:35 UTC, aminalaee commented
@sondrelg Thanks you for this. Yes, it looks good to me , and I don't think it would break anything.
I'll keep it open for a day or two to see if anyone has any objections though.

2021-09-01 17:40 UTC, aminalaee commented
Closes #359

2021-09-01 17:51 UTC, sondrelg commented
Ok cool, I'll add a test or two!

2021-09-01 18:19 UTC, aminalaee requested changes

2021-09-01 18:19 UTC, aminalaee commented on tests/test_databases.py
```suggestion


```

2021-09-02 08:13 UTC, aminalaee approved these changes
@sondrelg  Thanks for this.

2021-09-02 08:17 UTC, merged